import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

interface TermsPageProps {
  onBack: () => void
}

export function TermsPage({ onBack }: TermsPageProps) {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-4xl mx-auto">
        <Button variant="ghost" onClick={onBack} className="mb-6 gap-2">
          <ArrowLeft className="h-4 w-4" />
          Back to App
        </Button>

        <Card>
          <CardHeader>
            <CardTitle className="text-3xl">Terms and Conditions</CardTitle>
            <p className="text-sm text-muted-foreground">
              Last Updated: January 2026 | Version 1.0
            </p>
          </CardHeader>
          <CardContent className="prose prose-sm max-w-none dark:prose-invert">
            <div className="space-y-8">
              {/* Section 1 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">1. Introduction</h2>
                <p className="text-muted-foreground leading-relaxed">
                  These Terms and Conditions ("Terms") govern your access to and use of LinkedIn Content Generator ("Service"),
                  a personal project accessible at linkedin-content-frontend-smfw.onrender.com ("Website").
                </p>
                <p className="text-muted-foreground leading-relaxed mt-2">
                  By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part
                  of these Terms, you may not access the Service.
                </p>
                <div className="bg-muted/50 p-4 rounded-lg mt-4">
                  <p className="text-sm font-medium">
                    This is a personal project and is not operated by a registered company. The Service is provided on
                    an "as is" basis without any guarantees of availability, support, or continued operation.
                  </p>
                </div>
              </section>

              {/* Section 2 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">2. Definitions</h2>
                <ul className="space-y-2 text-muted-foreground">
                  <li><strong>"Service"</strong> - The LinkedIn Content Generator web application and all its features</li>
                  <li><strong>"User," "you," "your"</strong> - Any individual accessing or using the Service</li>
                  <li><strong>"Content"</strong> - All materials available through or generated by the Service</li>
                  <li><strong>"Generated Content"</strong> - LinkedIn posts and other content created by the Service using AI</li>
                  <li><strong>"API Keys"</strong> - Authentication credentials for third-party AI services (OpenAI, Anthropic)</li>
                  <li><strong>"Personal Data"</strong> - Information that identifies or could identify an individual</li>
                </ul>
              </section>

              {/* Section 3 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">3. Service Description</h2>
                <h3 className="text-lg font-medium mb-2">3.1 Overview</h3>
                <p className="text-muted-foreground leading-relaxed">
                  LinkedIn Content Generator is a free tool that:
                </p>
                <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
                  <li>Analyzes GitHub repositories</li>
                  <li>Generates LinkedIn post content using AI (OpenAI GPT or Anthropic Claude)</li>
                  <li>Helps users create professional content for their LinkedIn network</li>
                </ul>

                <h3 className="text-lg font-medium mb-2 mt-4">3.2 How It Works</h3>
                <ul className="list-disc list-inside text-muted-foreground space-y-1">
                  <li>You provide your own API keys from OpenAI and/or Anthropic</li>
                  <li>You connect your GitHub repositories for analysis</li>
                  <li>The Service uses AI to generate LinkedIn post suggestions</li>
                  <li>You review, edit, and use the generated content at your discretion</li>
                </ul>

                <h3 className="text-lg font-medium mb-2 mt-4">3.3 Free Service</h3>
                <p className="text-muted-foreground">
                  This Service is provided free of charge. There are no paid tiers, subscriptions, or premium features.
                </p>
              </section>

              {/* Section 4 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">4. User Eligibility</h2>
                <p className="text-muted-foreground leading-relaxed">
                  To use this Service, you must:
                </p>
                <ul className="list-disc list-inside text-muted-foreground mt-2 space-y-1">
                  <li>Be at least 18 years old</li>
                  <li>Have the legal capacity to enter into binding agreements</li>
                  <li>Not be prohibited from using the Service under applicable laws</li>
                  <li>Have valid API keys from OpenAI and/or Anthropic (obtained directly from those providers)</li>
                </ul>
              </section>

              {/* Section 5 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">5. API Keys and Third-Party Services</h2>

                <h3 className="text-lg font-medium mb-2">5.1 Your API Keys</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You are required to provide your own API keys from OpenAI (for GPT models) and/or Anthropic (for Claude models).
                </p>
                <div className="bg-destructive/10 border border-destructive/20 p-4 rounded-lg mt-3">
                  <p className="text-sm font-medium">You are solely responsible for:</p>
                  <ul className="list-disc list-inside text-sm mt-2 space-y-1">
                    <li>Obtaining API keys directly from these providers</li>
                    <li>Complying with OpenAI's and Anthropic's respective terms of service</li>
                    <li>All costs and charges incurred through your API usage</li>
                    <li>Maintaining the security of your API keys</li>
                    <li>Any consequences of API key misuse or compromise</li>
                  </ul>
                </div>

                <h3 className="text-lg font-medium mb-2 mt-4">5.2 API Key Storage</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Your API keys are stored in your browser's local storage and are encrypted. We do not store your API keys
                  on our servers. However, you should treat your API keys as sensitive credentials and should not use the
                  Service on shared or public computers.
                </p>

                <h3 className="text-lg font-medium mb-2 mt-4">5.3 Third-Party Services</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The Service integrates with GitHub, OpenAI, Anthropic, and LinkedIn. Your use of these third-party
                  services is governed by their respective terms. We are not responsible for third-party services,
                  their availability, or their handling of your data.
                </p>
              </section>

              {/* Section 6 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">6. AI-Generated Content Disclaimer</h2>

                <div className="bg-amber-500/10 border border-amber-500/30 p-4 rounded-lg">
                  <h3 className="text-lg font-medium mb-2">Important Notice</h3>
                  <p className="text-sm">
                    The Service uses artificial intelligence to generate content. AI-generated content:
                  </p>
                  <ul className="list-disc list-inside text-sm mt-2 space-y-1">
                    <li>May contain inaccuracies, errors, or misleading information</li>
                    <li>May not reflect current or accurate information about your projects</li>
                    <li>Should be reviewed and edited before use</li>
                    <li>May not be suitable for all purposes or audiences</li>
                  </ul>
                </div>

                <h3 className="text-lg font-medium mb-2 mt-4">Your Responsibility</h3>
                <p className="text-muted-foreground leading-relaxed">
                  You are solely responsible for reviewing all generated content before publishing, ensuring accuracy
                  and appropriateness, compliance with LinkedIn's terms of service, and any consequences of publishing
                  AI-generated content.
                </p>

                <h3 className="text-lg font-medium mb-2 mt-4">No Professional Advice</h3>
                <p className="text-muted-foreground leading-relaxed">
                  Generated content does not constitute professional, legal, financial, or career advice. Do not rely
                  on AI-generated content for important decisions.
                </p>
              </section>

              {/* Section 7 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">7. Acceptable Use</h2>
                <p className="text-muted-foreground leading-relaxed mb-3">
                  The Service is for personal, non-commercial content creation purposes. You may not:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-1">
                  <li>Use the Service for illegal purposes</li>
                  <li>Generate content that violates LinkedIn's terms or community guidelines</li>
                  <li>Generate misleading, defamatory, or harmful content</li>
                  <li>Attempt to reverse engineer or access the Service's source code</li>
                  <li>Use automated systems to abuse or overload the Service</li>
                  <li>Circumvent any access controls or usage limits</li>
                  <li>Use the Service to spam or engage in deceptive practices</li>
                </ul>
              </section>

              {/* Section 8 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">8. Privacy and Data Protection</h2>

                <h3 className="text-lg font-medium mb-2">Data We Collect</h3>
                <p className="text-muted-foreground leading-relaxed">
                  The Service may process GitHub repository data you choose to analyze (temporarily), usage data,
                  and browser local storage data (API keys, preferences).
                </p>

                <h3 className="text-lg font-medium mb-2 mt-4">Data We Do Not Collect</h3>
                <ul className="list-disc list-inside text-muted-foreground space-y-1">
                  <li>We do not store your API keys on our servers</li>
                  <li>We do not store your GitHub repository content permanently</li>
                  <li>We do not collect personal identification information</li>
                </ul>

                <h3 className="text-lg font-medium mb-2 mt-4">Singapore PDPA Compliance</h3>
                <p className="text-muted-foreground leading-relaxed">
                  We are committed to protecting your personal data in accordance with the Personal Data Protection
                  Act 2012 (PDPA) of Singapore. You have the right to access your personal data, correct inaccurate
                  data, and withdraw consent for data collection/use.
                </p>
              </section>

              {/* Section 9 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">9. Disclaimers</h2>
                <div className="bg-muted p-4 rounded-lg">
                  <p className="text-sm uppercase font-medium mb-2">Important Legal Notice</p>
                  <p className="text-sm text-muted-foreground">
                    THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS
                    OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
                    PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
                  </p>
                </div>
                <p className="text-muted-foreground leading-relaxed mt-4">
                  We do not guarantee that the Service will be uninterrupted, secure, or error-free; that generated
                  content will be accurate, useful, or appropriate; that the Service will meet your specific requirements;
                  or that the Service will continue to be available.
                </p>
              </section>

              {/* Section 10 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">10. Limitation of Liability</h2>
                <p className="text-muted-foreground leading-relaxed">
                  To the maximum extent permitted by Singapore law, we shall not be liable for any indirect, incidental,
                  special, consequential, or punitive damages; loss of profits, revenue, data, or goodwill; cost of
                  substitute services; damages arising from AI-generated content; or API charges incurred through
                  third-party services.
                </p>
                <p className="text-muted-foreground leading-relaxed mt-3">
                  Our total aggregate liability for any claims arising from these Terms or the Service shall not exceed S$100.
                </p>
                <p className="text-muted-foreground leading-relaxed mt-3">
                  <strong>Exceptions:</strong> Nothing in these Terms excludes or limits liability for death or personal
                  injury caused by negligence, fraud or fraudulent misrepresentation, or any liability that cannot be
                  limited under applicable Singapore law.
                </p>
              </section>

              {/* Section 11 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">11. Indemnification</h2>
                <p className="text-muted-foreground leading-relaxed">
                  You agree to indemnify and hold harmless the operator of this Service from any claims, damages, losses,
                  or expenses arising from your use of the Service, your violation of these Terms, your violation of
                  third-party rights, content you generate or publish using the Service, or your breach of third-party
                  terms of service.
                </p>
              </section>

              {/* Section 12 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">12. Termination</h2>
                <p className="text-muted-foreground leading-relaxed">
                  You may stop using the Service at any time. To remove your data, clear your browser's local storage
                  and disconnect your API keys from the interface.
                </p>
                <p className="text-muted-foreground leading-relaxed mt-3">
                  We may suspend or terminate access to the Service at any time, without notice, for any reason,
                  including violation of these Terms, abusive behavior, technical concerns, or discontinuation of
                  the project.
                </p>
              </section>

              {/* Section 13 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">13. Dispute Resolution</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Before filing any formal dispute, you agree to contact us to attempt to resolve the dispute informally.
                </p>
                <p className="text-muted-foreground leading-relaxed mt-3">
                  <strong>Governing Law:</strong> These Terms shall be governed by and construed in accordance with the
                  laws of the Republic of Singapore, without regard to conflict of law principles.
                </p>
                <p className="text-muted-foreground leading-relaxed mt-3">
                  <strong>Jurisdiction:</strong> Any disputes arising from these Terms shall be subject to the exclusive
                  jurisdiction of the courts of Singapore.
                </p>
              </section>

              {/* Section 14 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">14. General Provisions</h2>
                <ul className="space-y-3 text-muted-foreground">
                  <li><strong>Entire Agreement:</strong> These Terms constitute the entire agreement between you and us regarding the Service.</li>
                  <li><strong>Severability:</strong> If any provision is found unenforceable, the remaining provisions will continue in effect.</li>
                  <li><strong>Waiver:</strong> Our failure to enforce any right or provision does not constitute a waiver of such right or provision.</li>
                  <li><strong>Assignment:</strong> You may not assign these Terms without prior written consent. We may assign these Terms without restriction.</li>
                  <li><strong>Amendments:</strong> We may modify these Terms at any time by posting updated Terms on the Website. Continued use after changes constitutes acceptance.</li>
                </ul>
              </section>

              {/* Section 15 */}
              <section>
                <h2 className="text-xl font-semibold mb-3">15. Acknowledgments</h2>
                <p className="text-muted-foreground leading-relaxed">
                  By using the Service, you acknowledge that you have read and understood these Terms, agree to be bound
                  by these Terms, understand this is a personal project without commercial support, are responsible for
                  reviewing and verifying all AI-generated content, are responsible for your own API keys and associated
                  costs, and will comply with all applicable laws and third-party terms of service.
                </p>
              </section>

              {/* Disclaimer */}
              <section className="border-t pt-6 mt-8">
                <div className="bg-muted/50 p-4 rounded-lg">
                  <p className="text-xs text-muted-foreground">
                    <strong>DISCLAIMER:</strong> This Terms and Conditions document was generated as a template and should
                    be reviewed by a qualified legal professional before use. Laws and regulations change frequently.
                    This document does not constitute legal advice. The operator of LinkedIn Content Generator is
                    responsible for ensuring compliance with all applicable laws.
                  </p>
                </div>
              </section>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
